# Generated by Django 4.1.1 on 2022-09-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='priece',
            new_name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(default='good'),
        ),
    ]
